"""
BidRadar V2.0 enterprise procurement source configuration.

This module only defines large enterprise procurement platform metadata.
Crawler integration should be implemented separately.
"""

ENTERPRISE_KEYWORDS = [
    "纸箱",
    "包装箱",
    "瓦楞纸箱",
    "包装材料",
    "彩箱",
    "纸盒",
    "供应商征集",
    "供应商招募",
    "供应商入围",
    "年度采购",
]

ENTERPRISE_SOURCES = [
    {
        "name": "伊利集团",
        "industry": "乳制品",
        "homepage": "https://www.yili.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "蒙牛乳业",
        "industry": "乳制品",
        "homepage": "https://www.mengniu.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "海尔集团",
        "industry": "家电",
        "homepage": "https://www.haier.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "美的集团",
        "industry": "家电",
        "homepage": "https://www.midea.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "五粮液集团",
        "industry": "白酒",
        "homepage": "https://www.wuliangye.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "贵州茅台",
        "industry": "白酒",
        "homepage": "https://www.moutaichina.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "青岛啤酒",
        "industry": "啤酒饮料",
        "homepage": "https://www.tsingtao.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "农夫山泉",
        "industry": "饮料",
        "homepage": "https://www.nongfuspring.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "娃哈哈集团",
        "industry": "饮料",
        "homepage": "https://www.wahaha.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "海天味业",
        "industry": "调味品",
        "homepage": "https://www.haitian-food.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "A",
        "enabled": True,
    },
    {
        "name": "双汇发展",
        "industry": "食品加工",
        "homepage": "https://www.shuanghui.net/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "达利食品",
        "industry": "食品饮料",
        "homepage": "https://www.dali-group.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "今麦郎",
        "industry": "方便食品",
        "homepage": "https://www.jinmailang.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "康师傅",
        "industry": "方便食品",
        "homepage": "https://www.masterkong.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "统一企业中国",
        "industry": "食品饮料",
        "homepage": "https://www.uni-president.com.cn/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "格力电器",
        "industry": "家电",
        "homepage": "https://www.gree.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "海信集团",
        "industry": "家电",
        "homepage": "https://www.hisense.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "B",
        "enabled": True,
    },
    {
        "name": "TCL集团",
        "industry": "家电电子",
        "homepage": "https://www.tcl.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "C",
        "enabled": True,
    },
    {
        "name": "比亚迪",
        "industry": "汽车制造",
        "homepage": "https://www.bydglobal.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "C",
        "enabled": True,
    },
    {
        "name": "宁德时代",
        "industry": "新能源",
        "homepage": "https://www.catl.com/",
        "procurement_url": "",
        "keywords": ENTERPRISE_KEYWORDS,
        "priority": "C",
        "enabled": True,
    },
]
